GET http://localhost:4000/

###
POST http://localhost:4000/register
Content-Type: application/json

{
    "name": "abolfazl",
    "email": "abolfazlshabani.developer@gmail.com",
    "password": "123456789"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "abolfazlshabani.developer@gmail.com",
    "password": "123456789"
}
